### ISSUE TITLE
readonly input attribute or similar

### ISSUE THREAD

**Issue by santimacia** [bootstrap-tagsinput/bootstrap-tagsinput#112]
It's possible to use the readonly attribute? I tried to put it but when it's rendered the attribute disappears.

**Comment by KrishnaPG** [comment]
The disabled state PR(https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/166) vis good one to start with, but still the UI is not reflecting the "disabled" state. For example, below is the screenshot of one such control in disable state (but looks like it is functional until user clicks it and it does not respond). Perhaps removing the "x" marks in the individual items and removing the "all encompassing white box in the background" to show only the items could be useful.

![image](https://cloud.githubusercontent.com/assets/4610831/11013159/b3a53902-8527-11e5-807c-172fa5d62ba0.png)

Something like below (mockup, not real ) should do:
![image](https://cloud.githubusercontent.com/assets/4610831/11013185/94a6a436-8528-11e5-9d77-802853dd8d9b.png)

**Comment by ktohme** [comment]
I'm also looking for a possibility for really disabling the input field like KrishnaPG has advised

**Comment by drmalus** [comment]
Hi all!

I had the same problem.
My dirty hack is:
```css
.bootstrap-tagsinput .tag [data-role="remove"] { display: none; }
.bootstrap-tagsinput input { display: none; }
```

**Comment by Disane87** [comment]
I really would love the solution @KrishnaPG described.

**Comment by kimyu92** [comment]
@drmalus not a bad idea

using similar idea, to prevent input but allow user to remove
```css
.bootstrap-tagsinput {
   border: none;
   box-shadow: none;
}
.bootstrap-tagsinput input {
   display: none;
}
```
