### ISSUE TITLE
once max hit, no way to remove tags

### ISSUE THREAD

**Issue by gdibble** [bootstrap-tagsinput/bootstrap-tagsinput#341]
per https://github.com/timschlechter/bootstrap-tagsinput/blob/master/src/bootstrap-tagsinput.css#L46

i think this should be:
```css
.bootstrap-tagsinput .tag [data-role="remove"]:after,
.bootstrap-tagsinput-max .tag [data-role="remove"]:after {
  content: "x";
  padding: 0px 2px;
}
```
