### ISSUE TITLE
Width problem with typeahead tt-hint and tt-input stuck at 3em

### ISSUE THREAD

**Issue by jclee100** [bootstrap-tagsinput/bootstrap-tagsinput#344]
To reproduce:
Go to typeahead example: http://timschlechter.github.io/bootstrap-tagsinput/examples/
Type a long word such as "Amsterdam", the word gets cut off due to a 3em !important width inline style.

Both .tt-hint and .tt-input has this problem.

**Comment by alexbooker** [comment]
I have this problem too..

**Comment by alexbooker** [comment]
Solution: 

```css
.bootstrap-tagsinput input {
  min-width: 150px;  //change as wanted
 }
```

Source: https://github.com/timschlechter/bootstrap-tagsinput/issues/219
