### ISSUE TITLE
Type-ahead example does not work locally

### ISSUE THREAD

**Issue by alexbooker** [bootstrap-tagsinput/bootstrap-tagsinput#345]
I emulated the type-ahead [example](http://timschlechter.github.io/bootstrap-tagsinput/examples/) locally:  

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="public/components/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="public/components/bootstrap-tagsinput/dist/bootstrap-tagsinput.css">
  <link rel="stylesheet" type="text/css" href="http://timschlechter.github.io/bootstrap-tagsinput/examples/assets/app.css">
</head>
<body>

  <input type="text" value="Amsterdam,Washington" data-role="tagsinput" >

  <script src="public/components/jquery/dist/jquery.min.js"></script>
  <script src="public/components/bootstrap/dist/js/bootstrap.min.js"></script>
  <script src="public/components/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js"></script>
  <script src="public/components/typeahead.js/dist/typeahead.bundle.min.js"></script>
  <script>
    var citynames = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      prefetch: {
        url: 'http://timschlechter.github.io/bootstrap-tagsinput/examples/assets/citynames.json',
        filter: function(list) {
          return $.map(list, function(cityname) {
            return { name: cityname }; });
        }
      }
    });
    citynames.initialize();

    $('input').tagsinput({
      typeaheadjs: {
        name: 'citynames',
        displayKey: 'name',
        valueKey: 'name',
        source: citynames.ttAdapter()
      }
    });
  </script>
</body>
</html>
```

And this is the result I get:

![](http://i.imgur.com/8sQ4oPm.png)

What am I doing wrong?

Here are some things I have tried but did not work:

- I tried referencing your [custom css](http://timschlechter.github.io/bootstrap-tagsinput/examples/assets/app.css).
- I tried referencing bootstrap-theme. 

**Update 13:56**: I had a suspicion that at least one dependency had a breaking change, so I referenced the exact same dependencies as you: 

```html
<script src="http://timschlechter.github.io/bootstrap-tagsinput/examples/lib/jquery/dist/jquery.min.js"></script>
<script src="http://timschlechter.github.io/bootstrap-tagsinput/examples/lib/bootstrap-3/dist/js/bootstrap.min.js"></script>
<script src="http://timschlechter.github.io/bootstrap-tagsinput/examples/lib/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
<script src="http://timschlechter.github.io/bootstrap-tagsinput/examples/lib/typeahead.js/dist/typeahead.bundle.js"></script>
```

And now the type-ahead works like I would expect. Next, I need to figure out where the breaking change comes from..

**Update 14:09**: It _seems_ like the breaking change comes from [typeahead.js](Typeahead). Here is what I did to solve the problem:

- I referenced the [custom css](http://timschlechter.github.io/bootstrap-tagsinput/examples/assets/app.css) used on the demo page
- Instead of using the latest version of typeahead.js (`bower install typeahead.js`), I used version 10.0.4 (`bower install typeahead.js#0.10.4`) because that is the same version referenced from the examples page.

**Update 14:16**: Yeah. You **have** to reference version 10 of typeahead.js. Version [0.11.0](https://github.com/twitter/typeahead.js/blob/master/CHANGELOG.md#0110-april-25-2015) introduced a bunch of breaking changes...

**Comment by matthoiland** [comment]
Typeahead changed the class names from `0.10.5` to `0.11.0`. Most notably is changing `.twitter-typeahead` to `.typeahead`, and `.tt-dropdown-menu` to `.tt-menu`.

I'm using this CSS, which looks nearly identical the demo page example.

```CSS
.typeahead,
.tt-query,
.tt-hint {
  margin-bottom: 0;
}

.typeahead {
  background-color: #fff;
}

.typeahead:focus {
  border: 2px solid #0097cf;
}

.tt-query {
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
     -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}

.tt-hint {
  display: none;
  color: #999
}

.tt-menu {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1000;
  display: none;
  float: left;
  min-width: 160px;
  padding: 5px 0;
  margin: 2px 0 0;
  list-style: none;
  font-size: 14px;
  background-color: #ffffff;
  border: 1px solid #cccccc;
  border: 1px solid rgba(0, 0, 0, 0.15);
  border-radius: 4px;
  -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
  background-clip: padding-box;
}

.tt-suggestion {
    display: block;
  padding: 3px 20px;
  clear: both;
  font-weight: normal;
  line-height: 1.428571429;
  color: #333333;
  white-space: nowrap;
}

.tt-suggestion:hover {
  color: #ffffff;
  text-decoration: none;
  outline: 0;
  background-color: #428bca;
  cursor: pointer;
}

.tt-suggestion.tt-cursor {
  color: #fff;
  background-color: #0097cf;
}

.tt-suggestion p {
  margin: 0;
}
```
