### ISSUE TITLE
ReadOnly/Disabled remove 'x'

### ISSUE THREAD

**Issue by Stephen-Koludrovic** [bootstrap-tagsinput/bootstrap-tagsinput#430]
When a <input> or <select> field is disabled or read-only can the 'x' be removed as this is confusing for the end-user who sees an 'x' and just wants to click it with enthusiasm.

It would also be very nice if we could initialize and update the tags with 'x', 'o', ' '

**Comment by lucknerjb** [comment]
I agree with removing the X so users know they can't touch the tags. I don't quite understand what you mean with the following though:

> It would also be very nice if we could initialize and update the tags with 'x', 'o', ' '

**Comment by Stephen-Koludrovic** [comment]
Sorry, classic case of thinking it and not typing it. When initializing, an option could be created that allows different characters to replace the 'x'. This would give the developer the flexibility to convey various messages/meaning to the end user i.e. readonly could be 'o' while disabled could be ' ' (nothing)
$('input').tagsinput({
  tagChar: 'o'
}); 

And thanks for your efforts.

**Comment by lucknerjb** [comment]
I'm a little weary of adding too many options to the lib... we've already added a good bunch over the past few weeks. I agree that the X should be removed but I think that changing the char should be left to the dev to do as needed. I'm not sure it fits in the scope of the plugin.

**Comment by Stephen-Koludrovic** [comment]
Have a great Holiday break and thanks for considering the issue.

**Comment by GerardBalaoro** [comment]
My hack for this one is adding the ```static``` class on the bootstrap tags-input parent and put this on my css file:

```css
  .bootstrap-tagsinput.static .tag [data-role="remove"] {
    margin-left: 0px;
  }

  .bootstrap-tagsinput.static .tag [data-role="remove"]:after {
    content: none;
    padding: 0px 2px;
  }
```
Its a work around, simply 'hides' the x button. Hope it helps.
