### ISSUE TITLE
bootstrap-tagsinput with form-control

### ISSUE THREAD

**Issue by rendao** [bootstrap-tagsinput/bootstrap-tagsinput#458]
it's helpful to keep bootstrap input style

**Comment by merolhack** [comment]
Just change the style of ".bootstrap-tagsinput" to:
```css
.bootstrap-tagsinput {
  background-color: #fff;
  border: 1px solid #ccc;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  clear: both;
  display: block;
  padding: 4px 6px;
  color: #555;
  vertical-align: middle;
  border-radius: 4px;
  max-width: 100%;
  line-height: 22px;
  cursor: text;
}
```
